### pega token
POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic client-id-test:client-secret-test

grant_type=password&username=tresquatro&password=123

### lista todos produtos
GET http://localhost:8081/produtos
Authorization: Bearer zcGw2NVy9erl3_UO6PGHD8W8ibE

### pega um produto por id
GET  http://localhost:8081/produtos/44
Authorization: Bearer gpfgaxdXx-q05Gd6SfvYPN-iKRQ


### pega imagem do produto por id
GET  http://localhost:8081/produtos/imagem/11
Authorization: Bearer cPl9Os_-gTbt6GogqA10AwQLCBA

 

### cadastra produto com imagem
POST http://localhost:8081/produtos
Authorization: Bearer zcGw2NVy9erl3_UO6PGHD8W8ibE
Content-Type: multipart/form-data; boundary=MultipartBoundry

--MultipartBoundry
Content-Disposition: form-data; name="imagem"; filename="1.png"
Content-Type: image/png

< ./1.png
--MultipartBoundry
Content-Disposition: form-data; name="produto"
Content-Type: application/json

{"nome": "NOVOINF","marca": "INFNET","cotacoes": [{"nome": "INTERNET","fornecedor": "OLX","precoCotado": 20}]}
--MultipartBoundry--
 
 
###modifica um produto
PUT http://localhost:8081/produtos/44
Content-Type: application/json

{ 
  "nome": "MELAO",
  "marca": "MELAO",
  "cotacoes": null
}
###
 
### remove produto e imagem dele
DELETE http://localhost:8081/produtos/11
Authorization: Bearer zcGw2NVy9erl3_UO6PGHD8W8ibE



###
POST http://localhost:8081/produtos/cotacao
Content-Type: application/json

{
  "nome": "cocacola",
  "fornecedor": "coca",
  "precoCotado": 2
  
}

### todos usuarios
GET http://localhost:8081/usuarios



###
POST http://localhost:8081/usuarios
Content-Type: application/json

{
  "id": 0,
  "nome": "string",
  "email": "string",
  "password": "123",
  "username": "tresquatro"
}


###
GET http://localhost:8081/usuarios/1

###
POST http://localhost:8081/usuarios
Content-Type: application/json

{
    "nome": "gabr",
    "email": "g@b.e",
    "username": "g@b.e",
    "password": "123",
    "perfil": "admin"
}

###

POST http://localhost:8081/usuarios
Content-Type: application/json

{
    
    "email": "g@b.e",
    "username": "g@b.e",
    "password": "123",
    "perfil": "admin"
}
###

PUT http://localhost:8081/usuarios
Content-Type: application/json

{
    
    "email": "g2@b.e",
    "username": "g@b.e",
    "password": "123",
    "perfil": "admin",
}
###

DELETE http://localhost:8081/usuarios/1
