###
GET http://localhost:8081

###
# Authorization: Basic username:password
###
POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic client-id-test:client-secret-test

grant_type=password&username=tresquatro&password=123
// informações de um usuário



###
GET http://localhost:8081/produtos
Authorization: Bearer aDygfgus7anZFH0rF4aq7WwNAM0

###

GET  http://localhost:8081/produtos/1
Authorization: Bearer gpfgaxdXx-q05Gd6SfvYPN-iKRQ

### Cadastra produto
POST http://localhost:8081/produtos
Authorization: Bearer Y8-Fy-UuzIqhOnCbcuzymkzc_OY
Content-Type: application/json

{
    "nome": "Pasta de Banana",
    "marca": "Eskik",
    "cotacoes": [
    {
      "nome": "INTERNET",
      "fornecedor": "OLX",
      "precoCotado": 20
    }
  ]
}

### Cadastra produto
POST http://localhost:8081/produtos
Authorization: Bearer RmkMJZwrp7JXAWU_bSqav9aJBF4
Content-Type: multipart/form-data; boundary=MultipartBoundry

--MultipartBoundry
Content-Disposition: form-data; name="imagem"; filename="1.png"
Content-Type: image/png

< ./1.png
--MultipartBoundry
Content-Disposition: form-data; name="nome"
Content-Type: application/json

{"nome": "Pasta de Banana","marca": "Eskik","cotacoes": [{"nome": "INTERNET","fornecedor": "OLX","precoCotado": 20}]}
--MultipartBoundry--




###

PUT http://localhost:8081/produtos/1
Content-Type: application/json

{
    "marca": "Dell"
}
###

PATCH http://localhost:8081/produtos/1
Content-Type: application/json

{
    "nome": "Notebook"
}

###

DELETE http://localhost:8081/produtos/1
###



### todos usuarios
GET http://localhost:8081/usuarios



###
POST http://localhost:8081/usuarios
Content-Type: application/json

{
  "id": 0,
  "nome": "string",
  "email": "string",
  "password": "123",
  "username": "tresquatro"
}


###
GET http://localhost:8081/usuarios/1

###
POST http://localhost:8081/usuarios
Content-Type: application/json

{
    "nome": "Thiago",
    "email": "thi@go.com",
    "senha": "654321",
    "perfil": "admin"
}

###

POST http://localhost:8081/usuarios
Content-Type: application/json

{
    "nome": "Thiago",
    "email": "thi@go.com"
}
###

PUT http://localhost:8081/usuarios
Content-Type: application/json

{
    "nome": "Thiago",
    "email": "thi@go.com",
    "senha": "654321",
    "perfil": "admin"
}
###

DELETE http://localhost:8081/usuarios/1
